import { z } from "zod";

/**
 * The contracts of the evidence protocol.
 *
 * The organising distinction, and the one that most of this file exists to
 * enforce: a **search candidate** is a thing discovery suggested might be
 * relevant, and an **evidence record** is a thing that was actually retrieved.
 * Only the second can support or contradict a claim. A snippet is a reason to
 * fetch a page, not a reason to believe one.
 *
 * The second distinction is who may author what. Fields the model may write
 * are in `ClaimAdjudicationSchema` and `ClaimPlanSchema` and nowhere else.
 * Identity, provenance, timing, digests, protocol completion, and tool usage
 * are generated by trusted host code, so there is no schema in which the model
 * could express them even if it tried.
 */

/** The verification procedure that produced a receipt. Semantics, not a release number. */
export const METHOD_VERSION = "trustlayer-evidence-v1";

export const DEFAULT_MAX_CLAIMS = 3;
export const HARD_MAX_CLAIMS = 5;

// ---------------------------------------------------------------------------
// Request
// ---------------------------------------------------------------------------

export const FreshnessSchema = z.enum(["auto", "current", "recent", "timeless"]);
export type Freshness = z.infer<typeof FreshnessSchema>;

export const VerifyRequestSchema = z
  .object({
    /** The question the candidate output was supposed to answer. */
    task: z.string().min(1).max(12_000),
    /** The output under verification. Untrusted data, never instructions. */
    candidateOutput: z.string().min(1).max(40_000),
    /** Sources the candidate claims to have used. Fetched and tested, never trusted. */
    sourceUrls: z.array(z.string().url()).max(10).optional(),
    /**
     * Exactly what the caller cares about.
     *
     * When supplied, planning uses these instead of extracting claims, which
     * removes a model round-trip and spends the whole budget on what the
     * caller's next decision actually depends on. This is what makes a
     * one-claim `trust.check` cheap.
     */
    focusClaims: z.array(z.string().min(1).max(2_000)).max(HARD_MAX_CLAIMS).optional(),
    freshness: FreshnessSchema.default("auto"),
    maxClaims: z.number().int().min(1).max(HARD_MAX_CLAIMS).default(DEFAULT_MAX_CLAIMS),
  })
  .strict();

export type VerifyRequest = z.infer<typeof VerifyRequestSchema>;

// ---------------------------------------------------------------------------
// Claim plan
// ---------------------------------------------------------------------------

export const ImportanceSchema = z.enum(["critical", "material", "minor"]);
export type Importance = z.infer<typeof ImportanceSchema>;

export const ClaimFreshnessSchema = z.enum(["current", "recent", "timeless"]);
export type ClaimFreshness = z.infer<typeof ClaimFreshnessSchema>;

/** One claim selected for verification. `claimId` is assigned by the host. */
export interface PlannedClaim {
  readonly claimId: string;
  readonly text: string;
  readonly importance: Importance;
  readonly freshness: ClaimFreshness;
  /** True when the caller named this claim rather than the planner finding it. */
  readonly fromFocusClaims: boolean;
}

/** What the model may say when planning. It does not get to assign identifiers. */
export const PlannedClaimDraftSchema = z
  .object({
    text: z.string().min(1).max(2_000),
    importance: ImportanceSchema,
    freshness: ClaimFreshnessSchema,
  })
  .strict();

export const ClaimPlanSchema = z
  .object({
    claims: z.array(PlannedClaimDraftSchema).min(1).max(HARD_MAX_CLAIMS),
  })
  .strict();

export type ClaimPlanDraft = z.infer<typeof ClaimPlanSchema>;

// ---------------------------------------------------------------------------
// Discovery and evidence
// ---------------------------------------------------------------------------

/**
 * A source discovery suggested. Not evidence.
 *
 * Held in the ledger so the receipt can say how much was discovered against
 * how much was actually retrieved, and so a fetch can be linked back to the
 * search that proposed it.
 */
export interface SearchCandidate {
  readonly candidateId: string;
  readonly url: string;
  readonly title?: string;
  readonly snippet?: string;
  readonly query: string;
  readonly discoveredAt: string;
  /** The phase whose search produced this, for challenge-phase accounting. */
  readonly phase: string;
}

/** How a source came to be fetched. Decides whether it counts as independent. */
export type EvidenceOrigin = "independent" | "candidate_citation";

/**
 * A source that was actually retrieved.
 *
 * Every field here is written by trusted tool code. The model receives these
 * records but cannot mint, alter, or forge one, which is what makes the
 * receipt's provenance meaningful.
 */
export interface EvidenceRecord {
  readonly evidenceId: string;
  /** The URL as requested. */
  readonly url: string;
  /** The URL actually retrieved, after redirects. */
  readonly resolvedUrl: string;
  readonly domain: string;
  readonly title?: string;
  readonly retrievedAt: string;
  /** Quarantined plain text — what the verifier actually read. */
  readonly extractedText: string;
  /** SHA-256 of `extractedText`, so a receipt reader can pin what was read. */
  readonly contentSha256: string;
  /** The SharedOS tool call that produced this record. */
  readonly sourceToolCallId: string;
  /** The search candidate this fetch came from, when it came from one. */
  readonly searchCandidateId?: string;
  readonly origin: EvidenceOrigin;
  /** Set when the quarantine layer saw instruction-shaped content in the page. */
  readonly instructionLikeContent: boolean;
}

// ---------------------------------------------------------------------------
// Adjudication (the model's output)
// ---------------------------------------------------------------------------

export const ClaimStatusSchema = z.enum([
  "supported",
  "contradicted",
  "unverified",
  "not_falsifiable",
]);
export type ClaimStatus = z.infer<typeof ClaimStatusSchema>;

export const EvidenceReferenceSchema = z
  .object({
    /** Must be an evidenceId the ledger actually minted. Validated post-turn. */
    evidenceId: z.string().min(1).max(64),
    relation: z.enum(["supports", "contradicts"]),
    note: z.string().max(1_000),
  })
  .strict();

export type EvidenceReference = z.infer<typeof EvidenceReferenceSchema>;

export const ClaimAdjudicationSchema = z
  .object({
    claimId: z.string().min(1).max(64),
    status: ClaimStatusSchema,
    confidence: z.number().min(0).max(1),
    rationale: z.string().min(1).max(2_000),
    evidence: z.array(EvidenceReferenceSchema).max(10),
  })
  .strict();

export type ClaimAdjudication = z.infer<typeof ClaimAdjudicationSchema>;

export const AdjudicationSubmissionSchema = z
  .object({
    summary: z.string().min(1).max(4_000),
    adjudications: z.array(ClaimAdjudicationSchema).max(HARD_MAX_CLAIMS),
    /**
     * What the model noticed in untrusted content.
     *
     * Reported, not relied upon: the containment guarantee is the tool
     * catalogue, and this is a best-effort observation on top of it.
     */
    suspiciousInstructions: z
      .object({
        detected: z.boolean(),
        indicators: z.array(z.string().max(500)).max(20),
      })
      .strict(),
  })
  .strict();

export type AdjudicationSubmission = z.infer<typeof AdjudicationSubmissionSchema>;

// ---------------------------------------------------------------------------
// Receipt (the product)
// ---------------------------------------------------------------------------

export type OverallStatus = "supported" | "mixed" | "contradicted" | "unverified";
export type ProtocolStatus = "complete" | "partial" | "failed";

export interface ReceiptClaim {
  readonly claimId: string;
  readonly claim: string;
  readonly importance: Importance;
  readonly status: ClaimStatus;
  readonly confidence: number;
  readonly rationale: string;
  /** Evidence IDs that survived validation, in the relation the model gave. */
  readonly evidence: readonly EvidenceReference[];
  /** Set when the host changed the model's status, and why. */
  readonly adjusted?: string;
}

export interface ReceiptEvidence {
  readonly evidenceId: string;
  readonly url: string;
  readonly resolvedUrl: string;
  readonly domain: string;
  readonly title?: string;
  readonly retrievedAt: string;
  readonly contentSha256: string;
  readonly origin: EvidenceOrigin;
}

export interface ReceiptCoverage {
  readonly claimsSelected: number;
  readonly claimsChecked: number;
  readonly criticalClaimsTotal: number;
  readonly criticalClaimsChecked: number;
  readonly searchCandidates: number;
  readonly sourcesFetched: number;
  readonly distinctDomains: number;
}

/** Host-derived facts about what the protocol actually did. Never model-authored. */
export interface ReceiptChecks {
  readonly independentSearchPerformed: boolean;
  readonly sourcesFetched: boolean;
  readonly candidateCitationsChecked: boolean;
  readonly contradictionSearchPerformed: boolean;
  readonly evidenceReferencesValidated: boolean;
}

export interface ReceiptSecurity {
  readonly suspiciousInstructionsDetected: boolean;
  readonly indicators: readonly string[];
}

export interface ReceiptProvenance {
  readonly purpose: "trust.verify";
  readonly executionId: string;
  readonly traceId: string;
  readonly sharedosStatus: string;
  readonly toolsUsed: readonly string[];
  readonly startedAt: string;
  readonly completedAt: string;
  readonly durationMs: number;
}

/**
 * The deliverable.
 *
 * Deliberately contains no scalar trust score. A number like "87/100" reads as
 * a probability that the answer is true, which is precisely the thing
 * TrustLayer cannot establish. What it can establish — which sources were
 * retrieved, when, what they say, which phases ran, and under what authority —
 * is all here and is all inspectable.
 */
export interface EvidenceReceipt {
  readonly reportId: string;
  readonly methodVersion: string;
  readonly protocolStatus: ProtocolStatus;
  readonly overallStatus: OverallStatus;
  readonly summary: string;
  readonly claims: readonly ReceiptClaim[];
  readonly evidence: readonly ReceiptEvidence[];
  readonly coverage: ReceiptCoverage;
  readonly checks: ReceiptChecks;
  readonly security: ReceiptSecurity;
  readonly provenance: ReceiptProvenance;
  /** Phases that could not complete, when `protocolStatus` is not `complete`. */
  readonly incompletePhases?: readonly string[];
}
